version: "3"
services:
  postgres:
    image: postgres:14.5
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=spring_db
    ports:
      - 5432:5432
  
  backend:
    image: edrhianvalerioandres/akaeproject:1.0-v-postgres
    container_name: akae-spring-backend
    ports:
      - 8080:8080
    depends_on:
      - postgres