insert into COMPANIES (number_of_employees, phone_number, social_security_number, company_address, email, company_name, owner_name, company_type) values (32, '8427040473', '7934632643', '14528 Porter Hill', 'dantonacci0@yolasite.com', 'Cogidoo', 'Delaney Antonacci', 'QADirector');
insert into COMPANIES (number_of_employees, phone_number, social_security_number, company_address, email, company_name, owner_name, company_type) values (171, '9552811921', '9793562355', '3384 Moland Avenue', 'wmaton1@bbb.org', 'Edgeclub', 'Wyatt Maton', 'UCC filings');
insert into COMPANIES (number_of_employees, phone_number, social_security_number, company_address, email, company_name, owner_name, company_type) values (25, '2664256681', '9201179270', '33 Monument Center', 'gwackley2@wikia.com', 'Skiba', 'Gregorius Wackley', 'MFC');
insert into COMPANIES (number_of_employees, phone_number, social_security_number, company_address, email, company_name, owner_name, company_type) values (11, '5198390701', '5626269640', '38337 Farragut Drive', 'wjasper3@ebay.co.uk', 'Teklist', 'Wye Jasper', 'International Business');
insert into COMPANIES (number_of_employees, phone_number, social_security_number, company_address, email, company_name, owner_name, company_type) values (35, '9581007727', '4686820388', '60 Forest Dale Place', 'wchristene4@cloudflare.com', 'Camimbo', 'Wilek Christene', 'Professional Services');
insert into COMPANIES (number_of_employees, phone_number, social_security_number, company_address, email, company_name, owner_name, company_type) values (379, '3911902330', '5648107161', '645 Dryden Trail', 'mcarmichael5@soundcloud.com', 'Devbug', 'Mason Carmichael', 'HBV');
insert into COMPANIES (number_of_employees, phone_number, social_security_number, company_address, email, company_name, owner_name, company_type) values (61, '4079549480', '2364641882', '1577 Kings Alley', 'toxborough6@webmd.com', 'Realmix', 'Trev Oxborough', 'Urban Forestry');
insert into COMPANIES (number_of_employees, phone_number, social_security_number, company_address, email, company_name, owner_name, company_type) values (185, '8957114294', '9909705335', '01 Butterfield Plaza', 'mjupe7@bloglovin.com', 'Devify', 'Mabel Jupe', 'Green Belt');
insert into COMPANIES (number_of_employees, phone_number, social_security_number, company_address, email, company_name, owner_name, company_type) values (217, '6979368246', '5382069135', '57600 Continental Terrace', 'hmorrott8@npr.org', 'Snaptags', 'Hervey Morrott', 'Business Ethics');
insert into COMPANIES (number_of_employees, phone_number, social_security_number, company_address, email, company_name, owner_name, company_type) values (80, '4268764840', '5097743773', '63097 Eggendart Junction', 'ctelezhkin9@skyrock.com', 'Youfeed', 'Chrystal Telezhkin', 'VRF');

insert into OFFER (company_id, description, title) values (3, 'Environmental Specialist', 'Recruiter');
insert into OFFER (company_id, description, title) values (5, 'Accounting Assistant II', 'Information Systems Manager');
insert into OFFER (company_id, description, title) values (8, 'Engineer III', 'Accounting Assistant IV');
insert into OFFER (company_id, description, title) values (3, 'Senior Developer', 'Editor');
insert into OFFER (company_id, description, title) values (4, 'Geological Engineer', 'Junior Executive');
insert into OFFER (company_id, description, title) values (10, 'Operator', 'General Manager');
insert into OFFER (company_id, description, title) values (7, 'Software Test Engineer II', 'General Manager');
insert into OFFER (company_id, description, title) values (7, 'Marketing Assistant', 'Quality Control Specialist');
insert into OFFER (company_id, description, title) values (10, 'Structural Engineer', 'Chemical Engineer');
insert into OFFER (company_id, description, title) values (7, 'Budget/Accounting Analyst II', 'Civil Engineer');
